on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run migrations , clear cache for views, config and routes
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd htdocs/job_board
            git pull https://github.com/yousef-shaker1/job.git
            /opt/cpanel/ea-php81/root/usr/bin/php artisan migrate
            /opt/cpanel/ea-php81/root/usr/bin/php artisan optimize:clear

          host: 84.16.241.139
          user: b7_38284889
          port: 2204
          key: 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
          pass: R7nP9xQ2zL5
          args: -tt